<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="slearn-xbt" name="shoppingTest.LoginTestSD" tests="4" failures="1" timestamp="2021-06-20T15:35:37 MYT" time="6.330" errors="0">
  <testcase name="AddToCart" time="0.219" classname="shoppingTest.LoginTestSD"/>
  <system-out/>
  <testcase name="teardown" time="5.508" classname="shoppingTest.LoginTestSD">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [PRODUCTS--wrong] but found [PRODUCTS]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [PRODUCTS--wrong] but found [PRODUCTS]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at shoppingTest.LoginTestSD.teardown(LoginTestSD.java:206)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.afterRun(TestRunner.java:877)
at org.testng.TestRunner.run(TestRunner.java:599)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- teardown -->
  <system-out/>
  <testcase name="LoginTest" time="0.603" classname="shoppingTest.LoginTestSD"/>
  <system-out/>
  <testcase name="LoginTestCase" classname="shoppingTest.LoginTestSD">
    <skipped/>
  </testcase> <!-- LoginTestCase -->
  <system-out/>
</testsuite> <!-- shoppingTest.LoginTestSD -->
